fix: release pr action

diff --git a/.github/workflows/pr-release.yaml b/.github/workflows/pr-release.yaml
--- a/.github/workflows/pr-release.yaml
+++ b/.github/workflows/pr-release.yaml
@@ -49,7 +49,11 @@ jobs:
 
       - name: Set published version
         run: |
-          published_version=$(echo "${{ steps.release.outputs.version }}" | grep -oP '@\K([0-9]+\.){2}[0-9]+-pr-${{ github.event.pull_request.number }}-\d+')
+          published_version=$(echo "${{ steps.release.outputs.version }}" | grep -oP -m 1 '@fuel-ui/[^@]*@\K([0-9]+\.){2}[0-9]+-pr-${{ github.event.pull_request.number }}-\w+')
+          if [ -z "$published_version" ]; then
+            echo "Error: Published version not found"
+            exit 1
+          fi
           echo "::set-output name=published_version::$published_version"
         id: set_version
 
